
- alias: "Change light state every 30 seconds"
  triggers:
    - type: "interval"
      hours: 0
      minutes: 0
      seconds: 30
      
  conditions:
    - condition: "state"
      entity_id: "light"
      state: "off"
  actions:
    - service: "light.turn_on"
      entity_id: "light"


- alias: "Turn off light after 5 minutes"
  triggers:
    - type: "state"
      entity_id: "light"
      from: "on"
      to: "off"
      for: "00:05:00"
  conditions: []
  actions:
    - service: "light.turn_off"
      entity_id: "light"

- alias: "Turn off the light at 10:00 PM"
  triggers:
    - type: "cron"
      hour: 22
      minute: 0
  conditions: []
  actions:
    - service: "light.turn_off"
      entity_id: "light"