import os
import time
from datetime import datetime

from hestia.lib.hestia_logger import logger
from hestia.llm.llama_chat_completion import load_prompt, chat_completion
from hestia.text_to_speech.speech import TextToSpeechSystem
from hestia.text_to_speech.tts_utils import play_audio
from hestia.tools.random_scripts.advice import get_advice
from hestia.tools.reports.news_report import NewsReport
from hestia.tools.reports.weather_report import WeatherReport
from hestia.tools.system_and_utility.Alarm.alarm import Alarm
from hestia.tools.system_and_utility.scheduler import SchedulerManager

scheduler = SchedulerManager()

# add some global variables
REPORT_PATH = "hestia/tools/reports"
TTS_PATH = "hestia/text_to_speech/outputs"
PROMPT_PATH = "hestia/llm/prompts"
SCHEDULE_PATH = "hestia/tools/reports/schedule"


def generate_report(report_class):
    """Generate a report."""
    try:
        report = report_class()
        report.parse_information()
        report.generate_report_summary()
    except Exception as e:
        logger.error(f"Error generating report: {e}")


def morning_greeting():
    today = datetime.now().strftime("%b %d, %Y")
    logger.info(f"Generating morning greeting for {today}...")
    with open(f"{REPORT_PATH}/news/news_summary {today}.txt", "r") as file:
        news = file.read()
    with open(f"{REPORT_PATH}/weather/weather_report {today}.txt", "r") as file:
        weather = file.read()
    prompt = load_prompt("morning_greeting")
    
    greeting = chat_completion(
        system_prompt=prompt,
        user_prompt=f"""Today's information:
        Day of the week:{datetime.now().strftime("%A")}\
        Time is: {datetime.now().strftime("%I:%M %p")}
        Date: {today},
        Newss:\n{news}\n,
        weather:\n{weather}\n,
        Advice of the day:\n{get_advice()}\n
        """
    )
    tts = TextToSpeechSystem()
    tts.convert_text_to_speech(greeting,
                               output_dir=f"{TTS_PATH}/morning_greeting",
                               output_filename=f"{today}morning_greeting")


def play_report(report_type):
    """Play a report."""
    todays_date = datetime.now().strftime("%b %d, %Y")
    report_path = f"{TTS_PATH}/{report_type}/{todays_date}{report_type}.wav"
    play_audio(report_path)


def morning_preparation():
    """Prepare for the morning routine."""
    logger.info("Preparing for morning routine...")
    generate_report(NewsReport)
    generate_report(WeatherReport)
    morning_greeting()
    


def play_morning_greeting():
    """Play the morning greeting."""
    todays_date = datetime.now().strftime("%b %d, %Y")
    greeting_path = f"{TTS_PATH}/morning_greeting/{todays_date}morning_greeting.wav"
    play_audio(greeting_path)


def morning_presentation():
    """Play the morning presentation."""
    logger.info("Starting morning presentation...")
    alarm = Alarm()
    alarm.start()
    while alarm.is_active():
        time.sleep(1)
    time.sleep(5)
    play_morning_greeting()
    logger.info("Morning presentation complete. Cleaning up...")
    cleanup()


def cleanup():
    """Clean up the files generated by the morning routine."""
    logger.info("Cleaning up...")
    for file in os.listdir("hestia/text_to_speech/outputs"):
        if file.endswith(".wav"):
            os.remove(f"hestia/text_to_speech/outputs/{file}")
    for file in os.listdir("hestia/tools/reports/news"):
        if file.endswith(".txt"):
            os.remove(f"hestia/tools/reports/news/{file}")
    for file in os.listdir("hestia/tools/reports/weather"):
        if file.endswith(".txt"):
            os.remove(f"hestia/tools/reports/weather/{file}")
    logger.info("Cleanup complete.")
    for file in os.listdir("hestia/tools/reports/schedule"):
        if file.endswith(".txt"):
            os.remove(f"hestia/tools/reports/schedule/{file}")
    for file in os.listdir("hestia/tools/reports/morning_greeting"):
        if file.endswith(".wav"):
            os.remove(f"hestia/tools/reports/morning_greeting/{file}")

